### ISSUE TITLE
Fix `copy_to` arrange for `group_by`

### ISSUE THREAD

**Issue by colearendt** [rstudio/dbtest#8]
`group_by` verb needs an `arrange` for independence from different db behaviors with respect to sorting group by

**Comment by colearendt** [comment]
Just for the record, this fix broke Microsoft SQL Server, because it does not allow "order by" in subqueries... 😑 

Decisions, decisions.  Failures on Postgres because `group_by` does not natively sort... or failures on MSSQL because it cannot handle extra "order by".  Or database specific nonsense.  This will probably require more thought (and testing on more databases).
```
nanodbc/nanodbc.cpp:1344: HY000: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified., Statement(s) could not be prepared.,
```

**Comment by edgararuiz** [comment]
No problem, we can send the `arrange()` verb after `collect()`

**Comment by colearendt** [comment]
Ok.  I added `sort()` since we are using `pull()` and need to sort a vector.  Note that this is still a problem with testing `arrange` since `arrange(!!f) %>% pull()` means that `order by` is in a subquery for MSSQL.

**Comment by colearendt** [comment]
Merp.  I'm stuck on this.  `arrange` doesn't create a new column to `pull`... so we need a different pattern here... it just pulls the last column from the dataset... should we have `id`s or something so we can uniquely determine sort order?

**Comment by colearendt** [comment]
In search of a silver bullet, one problem with adding a `mutate` is for items that are only meant for an `arrange`... like `desc`: `arrange(desc(fld_double))`, which fails under `mutate(desc(fld_double))`.   Maybe letting pull just grab the last column is right... it's really tough to test `arrange`.
